MIN_PROFIT_PERCENT = 0.02
MAX_PROFIT_PERCENT = 0.05

BUY_SCORE_THRESHOLD = 70
SELL_SCORE_THRESHOLD = 60

COOLDOWN_PERIOD_SECONDS = 90

RISK_PERCENT = 2
MAX_REBUY_COUNT = 3

USE_TREND_FILTER = True
USE_VOLATILITY_FILTER = True
MAX_VOLATILITY_PERCENT = 3.0

MA_WINDOWS = [20, 50, 200]
RSI_PERIOD = 14
